var store = [
{name:"00001-poll.jpg",tags:["photo", "house", "estonia", "baltic sea"]},
{name:"00002-poll.jpg",tags:["photo", "house", "estonia", "baltic sea"]},
{name:"00003-poll.jpg",tags:["photo", "house", "estonia", "baltic sea"]},
{name:"00004-poll.jpg",tags:["photo", "house", "estonia", "baltic sea"]},
{name:"00005-poll.jpg",tags:["photo", "house", "estonia", "baltic sea"]},
{name:"00006-poll.jpg",tags:["photo", "house", "estonia", "baltic sea"]},
{name:"00007-poll.jpg",tags:["photo", "house", "estonia", "baltic sea"]},
{name:"00008-poll.jpg",tags:["photo", "house", "estonia", "baltic sea"]},
{name:"00009-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00010-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00011-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00012-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00013-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00014-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00015-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00016-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00017-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00018-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00019-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00020-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00021-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00022-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00023-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00024-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00025-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00026-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00027-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00028-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00029-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00030-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00031-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00032-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00033-weimaraner.jpg",tags:["photo", "animal", "weimaraner", "dog", "nature", "art"]},
{name:"00034-hochwasserhund.jpg",tags:["photo", "dog", "animal"]},
{name:"00035-segelboot.jpg",tags:["photo", "boat", "sail", "water"]},
{name:"00036-klammer.jpg",tags:["photo", "art", "cloth pin"]},
{name:"00037-airsexchampionship.jpg",tags:["photo", "air", "sex", "championship"]},
{name:"00038-airsexchampionship.jpg",tags:["photo", "air", "sex", "championship"]},
{name:"00039-boese.jpg",tags:["photo", "weimar", "art", "candle", "anna amalia bibliothek", "commercial"]},
{name:"00040-affe.jpg",tags:["photo", "monkey", "ape", "selfie"]},
{name:"00041-gaddafi.jpg",tags:["photo", "politics"]},
{name:"00042-gnuone.jpg",tags:["photo", "politics", "grumpy cat", "grumpy", "cat"]},
{name:"00043-lake.jpg",tags:["photo", "lake", "under water", "water"]},
{name:"00044-konigsberg.jpg",tags:["photo", "house", "architecture", "anthropomorphic"]},
{name:"00045-poolhouse.jpg",tags:["photo", "house", "architecture", "pool", "luxury", "water"]},
{name:"00046-poolhouse.jpg",tags:["photo", "house", "architecture", "pool", "luxury", "water"]},
{name:"00047-venedig.jpg",tags:["photo", "nude", "venice", "black and white"]},
{name:"00048-cats.jpg",tags:["photo", "cat", "heart", "pink", "animal"]},
{name:"00049-dali.jpg", tags:["photo", "black and white"]}];
